//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolanteNominaRC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VolanteNominaEntities : DbContext
    {
        public VolanteNominaEntities()
            : base("name=VolanteNominaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<LoginHistory> LoginHistories { get; set; }
        public virtual DbSet<PayrollSeenHistory> PayrollSeenHistories { get; set; }
        public virtual DbSet<ExceptionsEmployee> ExceptionsEmployees { get; set; }
        public virtual DbSet<PayrollSentHistory> PayrollSentHistories { get; set; }
    
        public virtual ObjectResult<GetSentPayrollsGrouped_Result> GetSentPayrollsGrouped()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSentPayrollsGrouped_Result>("GetSentPayrollsGrouped");
        }
    }
}
